<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Devnet.Vault.Domain\Devnet.Vault.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Auth\Handlers\" />
    <Folder Include="Features\Auth\DTOs\" />
    <Folder Include="Features\Auth\Queries\" />
    <Folder Include="Features\VaultItems\Handlers\" />
    <Folder Include="Features\VaultItems\Commands\" />
    <Folder Include="Features\VaultItems\DTOs\" />
    <Folder Include="Features\VaultItems\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="libphonenumber-csharp" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" />
	<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
	<PackageReference Include="MediatR" />
  </ItemGroup>

</Project>